# Generated by Django 4.2.7 on 2023-11-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('players', '0002_alter_match_options_match_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_played', models.TimeField(default=0)),
                ('throw_count', models.PositiveIntegerField(default=0)),
                ('goal_three_count', models.PositiveIntegerField(default=0)),
                ('goal_two_count', models.PositiveIntegerField(default=0)),
                ('goal_penalty_count', models.PositiveIntegerField(default=0)),
                ('rebound_home', models.PositiveIntegerField(default=0)),
                ('rebound_away', models.PositiveIntegerField(default=0)),
                ('assist', models.PositiveIntegerField(default=0)),
                ('interception', models.PositiveIntegerField(default=0)),
                ('loss', models.PositiveIntegerField(default=0)),
                ('block_shot', models.PositiveIntegerField(default=0)),
                ('fouls_player', models.PositiveIntegerField(default=0)),
                ('fouls_opponent', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('is_finished', 'date')},
        ),
        migrations.AddField(
            model_name='match',
            name='team_away_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_home_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PlayerStatistics',
        ),
        migrations.AddField(
            model_name='matchstatistics',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.match'),
        ),
        migrations.AddField(
            model_name='matchstatistics',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
    ]
