# Generated by Django 4.2.7 on 2023-11-26 15:16

from django.db import migrations, models
import players.models


class Migration(migrations.Migration):
    dependencies = [
        ('players', '0003_matchstatistics_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstatistics',
            name='time_played',
            field=models.TimeField(default='00:00:00', validators=[players.models.validate_time_range]),
        ),
    ]
