# Generated by Django 4.2.7 on 2023-11-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('players', '0004_alter_matchstatistics_time_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
