# Generated by Django 4.2.7 on 2023-11-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('players', '0005_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='place',
            field=models.TextField(default='ул. Биатлонная, 25Б'),
        ),
    ]
