# Generated by Django 4.2.7 on 2023-11-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('players', '0006_match_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
