# Generated by Django 4.2.7 on 2023-11-28 13:56

from django.db import migrations, models
import django.db.models.deletion
import players.models


class Migration(migrations.Migration):
    dependencies = [
        ('players', '0008_alter_player_birth_date_alter_player_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstatistics',
            name='assist',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Голевые передачи'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='block_shot',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Блокшоты'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='fouls_opponent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Фолы соперника'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='fouls_player',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Фолы игрока'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='goal_penalty_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Штрафные'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='goal_three_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='goal_two_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='interception',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Перехват'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='loss',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Потери'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='players.match', verbose_name='Матч'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='players.player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='rebound_away',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ЧШ'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='rebound_home',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='СШ'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='throw_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество бросков'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='time_played',
            field=models.TimeField(blank=True, default='00:00:00', null=True,
                                   validators=[players.models.validate_time_range], verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
